### ISSUE TITLE
Publicar en Google Play

### ISSUE THREAD

**Issue by jgg1009** [aom1008/GESPRO_PracticaGestionTareas_2021#19]
https://support.google.com/googleplay/android-developer/answer/113469#privacy

https://www.raywenderlich.com/122114/android-app-distribution-tutorial-zero-google-play-store

**Comment by aom1008** [comment]
*Añadidas fotos de la aplicacion*

**Comment by aom1008** [comment]
https://play.google.com/store/apps/details?id=com.davidmiguel.gobees
