### ISSUE TITLE
Crear pagina web

### ISSUE THREAD

**Issue by eod1001** [aom1008/GESPRO_PracticaGestionTareas_2021#34]
https://startbootstrap.com/template-overviews/new-age/
http://www.grabon.in/mobile-apps/

http://bronto.github.io/javasphinx/

**Comment by eod1001** [comment]
añade hasta 7 commits hasta terminar la pag web. 
http://gobees.io/

**Comment by jgg1009** [comment]
Add google play link #34

**Comment by jgg1009** [comment]
Update .gitignore #34

**Comment by jgg1009** [comment]
Finish website #34

**Comment by jgg1009** [comment]
Minor fixes and compress imgs #34

**Comment by jgg1009** [comment]
Minor changes #34

**Comment by jgg1009** [comment]
Minor changes #34

**Comment by jgg1009** [comment]
Add docs link #34

**Comment by jgg1009** [comment]
http://gobees.io/
