### ISSUE TITLE
Grabar discos

### ISSUE THREAD

**Issue by mmb1009** [aom1008/GESPRO_PracticaGestionTareas_2021#38]
- Código fuente app
- Ejecutable app
- Herramientas
- Plataforma de desarrollo del algoritmo
- Herramienta de conteo de abejas
- Documentación
- Memoria
- Anexos
- JavaDoc
- Dataset de videos
**### README**
- Repositorio GoBees
- Repositorio prototipos
- Repositorio dependencia OpenCV

**Comment by aom1008** [comment]
Add cd cover #38

**Comment by aom1008** [comment]
Add cd cover #38
